### ISSUE TITLE
Package 'acceptance-tests' has a glob that resolves to an empty file list

### ISSUE THREAD

**Issue by charyorde** [cloudfoundry-incubator/docker-registry-release#1] opened 2015-06-06 19:14 UTC
On `bosh create release --force`

```
Building acceptance-tests...
Package 'acceptance-tests' has a glob that resolves to an empty file list: github.com/cloudfoundry-incubator/docker-registry-acceptance-tests/bin/*
```

**Comment by hsiliev** [comment] 2015-06-06 20:22
You need to run `./scripts/update` to clone the sub-modules as well.

**Comment by hsiliev** [comment] 2015-06-06 20:31
Added a section for initial setup. The instructions there should get you going. Closing the issue. Please reopen if you still have problems.

**Closed as completed by hsiliev** 2015-06-06 20:31 UTC

**Comment by charyorde** [comment] 2015-06-07 07:59
Thanks. However, I can't get the registry to listen on port 5000 even though it started to listen on port 5000

```
root@8db550ff-f8a2-4057-8451-8162b5b7ea81:~# cat /var/vcap/sys/log/docker_registry/stderr.log
[2015-06-06 21:17:39 +0000] [1] [INFO] Starting gunicorn 19.1.1
[2015-06-06 21:17:39 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2015-06-06 21:17:39 +0000] [1] [INFO] Using worker: gevent
[2015-06-06 21:17:39 +0000] [11] [INFO] Booting worker with pid: 11
[2015-06-06 21:17:39 +0000] [12] [INFO] Booting worker with pid: 12
[2015-06-06 21:17:39 +0000] [14] [INFO] Booting worker with pid: 14
[2015-06-06 21:17:39 +0000] [16] [INFO] Booting worker with pid: 16
06/Jun/2015:21:17:39 +0000 WARNING: Cache storage disabled!
06/Jun/2015:21:17:39 +0000 WARNING: LRU cache disabled!
06/Jun/2015:21:17:39 +0000 WARNING: Cache storage disabled!
06/Jun/2015:21:17:39 +0000 WARNING: LRU cache disabled!
06/Jun/2015:21:17:39 +0000 WARNING: Cache storage disabled!
06/Jun/2015:21:17:39 +0000 WARNING: LRU cache disabled!
06/Jun/2015:21:17:39 +0000 WARNING: Cache storage disabled!
06/Jun/2015:21:17:39 +0000 WARNING: LRU cache disabled!
06/Jun/2015:21:17:39 +0000 WARNING: Another process is creating the search database
root@8db550ff-f8a2-4057-8451-8162b5b7ea81:~# netstat -an | grep -i listen
tcp        0      0 127.0.0.1:8400          0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:8500          0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:53            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:2822          0.0.0.0:*               LISTEN
tcp        0      0 10.244.2.6:8301         0.0.0.0:*               LISTEN
tcp6       0      0 :::8080                 :::*                    LISTEN
tcp6       0      0 :::4243                 :::*                    LISTEN
tcp6       0      0 :::33331                :::*                    LISTEN
tcp6       0      0 :::22                   :::*                    LISTEN
tcp6       0      0 :::2825                 :::*                    LISTEN
```

**Comment by hsiliev** [comment] 2015-06-07 08:56
The port is currently defaulting to 8080:
https://github.com/cloudfoundry-incubator/docker-registry-release/blob/master/jobs/docker_registry/spec#L12

You can change it using the `docker_registry.address` property in the manifest. You can do this by providing custom `properties-overrides.yml` file instead of the current empty one (https://github.com/cloudfoundry-incubator/docker-registry-release/blob/master/manifest-generation/bosh-lite-stubs/property-overrides.yml). You can also directly edit the generated manifest of course.

**Comment by charyorde** [comment] 2015-06-07 10:08
Thanks. That explains it.

**Comment by charyorde** [comment] 2015-06-07 12:46
How can I enable https in the registry?

**Comment by georgethebeatle** [comment] 2015-06-07 13:17
This is not yet supported, but it is planned so stay tuned. We have [this story](https://www.pivotaltracker.com/n/projects/1003146/stories/87137448) in tracker. If you want to dig deeper yourself you should read [this article](https://docs.docker.com/registry/deploying/#configure-nginx-with-a-v1-and-v2-registry) on deploying a production-ready registry instance. Registry v 2.0 has native support for TLS, while for Registry v1.0 you need to plug in a nginx proxy for SSL termination. Keep in mind that if you secure your registry with a self-signed certificate it is still considered insecure so you need to keep the allow-insecure-registry settings in the [diego stub](https://github.com/cloudfoundry-incubator/docker-registry-release/blob/c9a76a99d6ab6dd18aa1e2812b1ef6d7440765aa/stubs-for-diego-release/bosh-lite-property-overrides.yml).

**Comment by charyorde** [comment] 2015-06-07 13:37
Thanks. One more thing please. What about authentication? How does the registry handle authentication? Can I use CF default auth credentials (i.e admin/admin)? If yes, where do I specify this?

**Comment by georgethebeatle** [comment] 2015-06-07 14:04
The registry uses `index.docker.io` for authentication by default. If you are using public images you need not worry about anyhing, if you are using private images you have to have an account @ DockerHub. [Their docs](https://github.com/docker/docker-registry#authentication-options) point to other authentication options as well, but I doubt we will need these for the scope of this project (which is local caching of the upstream images). I believe it is also possible to install an `nginx` proxy in front of the registry and configure that for some custom authentication.

**Comment by charyorde** [comment] 2015-06-07 14:30
Now I think this is where things get messy. When I use public images, I get this error when I do a `cf docker-push`

```
06-Jun-2015 20:21:26    OK
06-Jun-2015 20:21:26    TIP: Use 'cf restage' to ensure your env variable changes take effect
06-Jun-2015 20:21:26    FAILED
06-Jun-2015 20:21:26    Server error, status code: 500, error code: 170011, message: Stager error: staging failed: missing docker registry
```

With private images, I don't get these errors.

Full `cf docker-push` command:

```
cf docker-push "$1" "$2" "$3" --no-start
cf set-env "$1" DIEGO_DOCKER_CACHE true
cf start "$1"
```

Also, I've gone through the docker registry auth docs. But my question now is where in docker-registry-release should these authentication configs be placed?

Also, if I need to push images, should I specify `10.244.2.6:8080/namespace/repository` or I use `index.docker.io/namespace/repository`?

**Comment by georgethebeatle** [comment] 2015-06-07 20:03
First, the second part of your question: 

For now Docker-registry-release does not support custom authentication. So currently no authentication config can be placed in the release. Its intent is to serve as a cache for the images from Docker Hub. Can you elaborate on what you are trying to achieve?

When you push docker images to a private registry you normally specify `10.244.2.6:8080/namespace/repository`, but in the case of `docker-registry-release` you are not supposed to push to this private registry - it is internal and will be secured so that it is unreachable for the developer. If you need a private registry to push to then you need to spin up your own.

**Comment by charyorde** [comment] 2015-06-07 20:25
Resolved. I simply build and push like this:

```
docker build -t 10.244.2.6:8080/yookore-statics .
docker push 10.244.2.6:8080/yookore-statics
```

This is what I want to achieve. I actually thought this is the use case the `docker-registry-release` is built for. I think it's cool to use it as a private registry if it can support storing the images in external volumes.

**Comment by georgethebeatle** [comment] 2015-06-07 20:36
Well, initially we thought that it may be used to push your images directly to it, but then it turned out that this won't be secure enough as this will be used to store cached copies of many private images belonging to different users. So if we let all developers to access it they will be able to pull these images which is not desired. So we decided that this registry should be fully secured and inaccessible to no one but Diego. Right now you are able to push to it just because we're not done securing it yet.

By the way if you just want to experiment with running docker images form your private repo on top of Diego you may want to check out [lattice](http://lattice.cf/) if you haven't already. It gives you a very minimal Diego runtime and they have [private docker registry support](http://lattice.cf/docs/private-docker-registry/)

**Comment by georgethebeatle** [comment] 2015-06-07 20:48
And for the "missing docker registry" thing: How dexactly do you docker-push - what image name do you pass in? It seems that for some reason the registry is not registred in consul if you're seeing this error. Maybe you can grep the `stager` log file for a debug message containing `docker-registry-consul-services`

**Comment by charyorde** [comment] 2015-06-08 06:04
I'm trying a public repository now and I'm getting a StagingError:

```
OUT Created app with guid 41c7042d-cfa2-4dd4-a0bd-6e8055eb4636
OUT Updated app with guid 41c7042d-cfa2-4dd4-a0bd-6e8055eb4636 ({"route"=>"50e877b5-1258-438d-a69e-afd8e7e0dc9c"})
OUT Updated app with guid 41c7042d-cfa2-4dd4-a0bd-6e8055eb4636 ({"environment_json"=>"PRIVATE DATA HIDDEN"})
OUT Updated app with guid 41c7042d-cfa2-4dd4-a0bd-6e8055eb4636 ({"state"=>"STARTED"})
OUT Creating container
OUT Successfully created container
OUT Staging...
ERR Staging Failed
ERR Failed to stage application: staging failed
```

Full `docker-push` command

```
cf docker-push yookore-statics yookoreadmin/yookore-statics -c "node.sh" --no-start
cf set-env yookore-statics DIEGO_DOCKER_CACHE true
cf start yookore-statics
```

**Comment by charyorde** [comment] 2015-06-08 20:39
Here's the relevant part of the stager:

```
{"timestamp":"1433795594.978518486","source":"stager","message":"stager.completion-handler.task-complete-callback-received.cc-client.delivering-staging-response","log_level":1,"data":{"guid":"41c7042d-cfa2-4dd4-a0bd-6e8055eb4636-72c1b5b6018e4b2faf53489802dddeaf","payload":"{\"execution_metadata\":\"\",\"detected_start_command\":null,\"error\":{\"id\":\"StagingError\",\"message\":\"staging failed\"}}","session":"4.29.1"}}
```

I also tried with this `cf docker-push yookore-statics 10.244.2.6:8080/yookore-statics -c 'node server.js'`

Don't know why `detected_start_command` is null. Any ideas please?

**Comment by georgethebeatle** [comment] 2015-06-11 07:52
Strange, I tried it on local bosh-lite instance and got a different error. Are you sure your cf and diego versions are compatible? You can check [here](https://github.com/cloudfoundry-incubator/diego-cf-compatibility). I will reinstall my local system pulling the latest changes and will try again.

**Comment by charyorde** [comment] 2015-06-11 07:56
Yes they are. I also consulted the compatibility docs.

I've switched back to normal `cf push` for now. If you need me to test things further, I'm available to help.

**Comment by georgethebeatle** [comment] 2015-06-11 14:17
Did you try pushing without `-c` option?

**Comment by charyorde** [comment] 2015-06-11 14:23
Yes I did. Got same `StagingError`

**Comment by georgethebeatle** [comment] 2015-06-11 16:07
By the way where do you get the image from? I am getting a different error, becasue docker cannot find the image on DockerHub:

```
$ docker pull yookoreadmin/yookore-statics
Pulling repository yookoreadmin/yookore-statics
FATA[0001] Error: image yookoreadmin/yookore-statics:latest not found
```

Is this a private repo?

**Comment by charyorde** [comment] 2015-06-11 16:13
That's because I made it private since public doesn't work at all.

**Comment by georgethebeatle** [comment] 2015-06-12 07:35
```

**Comment by georgethebeatle** [comment] 2015-06-12 07:40
The following:

```
cf docker-push app cloudfoundry/diego-docker-app:latest -c "/myapp/dockerapp" --no-start
cf set-env app DIEGO_DOCKER_CACHE true
cf start app
```

seems to work, so I wonder what's the difference. One thing I notice is that you are giving a relative path - have tried absolute instead?

Another thing might be the user that runs your app - currently Garden has the limitation that your app should be run by a non-privileged user. Is your app run as root?

And finally, it would be helpful if you provide a public copy of the image you are testing with, so that I can reproduce and investigate further.

Oh, and one more thing - did you try running your image without the docker cache enabled? Like

```
cf docker-push yookore-statics yookoreadmin/yookore-statics -c "node.sh"
```

Does the problem still occur?

**Comment by charyorde** [comment] 2015-06-12 11:27
Thanks for this. However, what do you mean by relative path?

Also, I don't understand the context of what you mean by "the user that runs the app". Are you referring to what user executes `cf docker-push` or what user executes the docker build?

I've made the image public. see `yookoreadmin/yookore-statics`.

Yes, I did try without the docker cache enabled. I understand it's only useful if your docker image is in a private repo. So yes, I did.

**Comment by georgethebeatle** [comment] 2015-06-12 14:43
By relative path I mean specifying `/myapp/dockerapp` vs `dockerapp` alone. I pulled the container and ssh'd into it. And I could not find a `node.sh` executable. `find / -name node.sh` returned nothing.

By looking at what is inside the image I came to the conclusion that maybe a sensible way to start it is this: `docker run -d yookoreadmin/yookore-statics node /data/server.js`

However I can see that the server listens on port 3005, which is a problem right now, as Diego still supports only 8080 and does not respect the `EXPOSE` directive form the Dockerfile. But if you rebuild he image to `EXPOSE 8080` (and run the server on that port) then I assume that you could push it this way:

```
cf docker-push yookore-statics yookoreadmin/yookore-statics -c "node /data/server.js" --no-start
cf set-env yookore-statics DIEGO_DOCKER_CACHE true
cf start yookore-statics
```

Hope this helps

**Comment by charyorde** [comment] 2015-06-12 17:09
Hmm. Didn't realize that when you specify `-c` to `cf docker-push`, it searches within the container. The `node.sh` resides on a CI.

The server only listens on `3005` on local box. It makes use of `process.env.VCAP_APP_PORT` on CF dev space.

Now, I've made it private. Can you try again, just to be sure if this would work with a private repo. I want to see how this works with a private repo.

**Comment by georgethebeatle** [comment] 2015-06-15 14:44
Unfortunately I can't try it with the image being private, because I do not know your Docker Hub credentials. Private docker image support is brand new and the cli is not updated to prompt you for user/password, but you can do the following:

```
cf curl /v2/apps -X POST -d '{"name":"app","memory":512,"instances":1,"disk_quota":1024,"space_guid":"YOUR_SPACE_GUID","docker_image":"YOUR_IMAGE","diego":true, "docker_credentials_json" : {"docker_user":"USER","docker_password":"PASSWORD","docker_email":"dummy@example.com"} }'
```

This will create a stopped app from your private image. You can see your space guid by executing `cf space YOUR_SPACE --guid`. Then you need to start the app by executing `cf start app`

You can try this, but in general it shouldn't make any difference from the public image case. Only that you will authenticate in front of the Docker Hub. So if you come up with the correct start command it should work both ways.
